coverage:
  status:
    project:
      default:
        target: 30%
        threshold: 5%
    patch:
      default:
        target: 30%
        threshold: 5%

ignore:
  - "**/R.class"
  - "**/R$*.class"
  - "**/BuildConfig.*"
  - "**/*Test*.*"
  - "**/di/**"
  - "**/module/**"
  - "**/common/**"
  - "**/ui/**"
  - "**/App.kt"
  - "**/MovieExplorerApp.kt"
  - "**/*Screen.kt"
  - "**/*ScreenKt*"
  - "**/*_Factory*"
  - "**/*_HiltModules*"
  - "**/*_GeneratedInjector*"
  - "**/*_BindsModule*"
  - "**/*_KeyModule*"
  - "**/*_ProvideFactory*"
  - "**/*_InstanceHolder*"
  - "**/*_Factory$*"
  - "**/*_HiltModules$*"
  - "**/*_GeneratedInjector$*"
  - "**/*_BindsModule$*"
  - "**/*_KeyModule$*"
  - "**/*_ProvideFactory$*"
  - "**/*_InstanceHolder$*"
  - "**/dagger/**"
  - "**/hilt_aggregated_deps/**"
  - "**/hilt_aggregatedroot/**"
  - "**/processedrootsentinel/**"
  - "**/*_Factory.java"
  - "**/*_HiltModules.java"
  - "**/*_GeneratedInjector.java"
  - "**/*_BindsModule.java"
  - "**/*_KeyModule.java"
  - "**/*_ProvideFactory.java"
  - "**/*_InstanceHolder.java"

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
