name: Code Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Run tests with coverage
      run: ./gradlew jacocoTestReport
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        directory: ./app/src/main/java
        ignore: |
          **/R.class
          **/R$*.class
          **/BuildConfig.*
          **/*Test*.*
          **/di/**
          **/module/**
          **/common/**
          **/ui/**
          **/App.kt
          **/MovieExplorerApp.kt
          **/*Screen.kt
          **/*ScreenKt*
          **/*_Factory*
          **/*_HiltModules*
          **/*_GeneratedInjector*
          **/*_BindsModule*
          **/*_KeyModule*
          **/*_ProvideFactory*
          **/*_InstanceHolder*
          **/*_Factory$*
          **/*_HiltModules$*
          **/*_GeneratedInjector$*
          **/*_BindsModule$*
          **/*_KeyModule$*
          **/*_ProvideFactory$*
          **/*_InstanceHolder$*
          **/dagger/**
          **/hilt_aggregated_deps/**
          **/hilt_aggregatedroot/**
          **/processedrootsentinel/**
          **/*_Factory.java
          **/*_HiltModules.java
          **/*_GeneratedInjector.java
          **/*_BindsModule.java
          **/*_KeyModule.java
          **/*_ProvideFactory.java
          **/*_InstanceHolder.java
